In [3]:
import pandas as pd
data = pd.read_csv("bwq.csv")
data

,Beach Name,Measurement Timestamp,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life,Measurement Timestamp Label,Measurement ID
0,Montrose Beach,08/30/2013 08:00:00 AM,20.3,1.18,0.891,0.080,3.0,9.4,8/30/2013 8:00 AM,MontroseBeach201308300800
1,Ohio Street Beach,05/26/2016 01:00:00 PM,14.4,1.23,NaN,0.111,4.0,12.4,05/26/2016 1:00 PM,OhioStreetBeach201605261300
2,Calumet Beach,09/03/2013 04:00:00 PM,23.2,3.63,1.201,0.174,6.0,9.4,9/3/2013 4:00 PM,CalumetBeach201309031600
3,Calumet Beach,05/28/2014 12:00:00 PM,16.2,1.26,1.514,0.147,4.0,11.7,5/28/2014 12:00 PM,CalumetBeach201405281200
4,Montrose Beach,05/28/2014 12:00:00 PM,14.4,3.36,1.388,0.298,4.0,11.9,5/28/2014 12:00 PM,MontroseBeach201405281200
...,...,...,...,...,...,...,...,...,...,...
34918,Ohio Street Beach,09/12/2017 12:00:00 PM,19.9,2.61,NaN,0.187,3.0,10.5,09/12/2017 12:00 PM,OhioStreetBeach201709121200
34919,Ohio Street Beach,09/12/2017 01:00:00 PM,19.8,0.00,NaN,0.187,3.0,10.5,09/12/2017 1:00 PM,OhioStreetBeach201709121300
34920,Ohio Street Beach,09/12/2017 03:00:00 PM,22.3,0.00,NaN,0.187,3.0,10.5,09/12/2017 3:00 PM,OhioStreetBeach201709121500
34921,Ohio Street Beach,09/12/2017 05:00:00 PM,21.1,26.97,NaN,0.187,3.0,9.4,09/12/2017 5:00 PM,OhioStreetBeach201709121700
34922,Ohio Street Beach,09/12/2017 06:00:00 PM,21.3,27.55,NaN,0.187,3.0,9.4,09/12/2017 6:00 PM,OhioStreetBeach201709121800